// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzw8I6aFYdp2v2Du_NRxlALQtTq9CHAc0',
    appId: '1:400224458947:web:bce5babab0fd6474c2aa76',
    messagingSenderId: '400224458947',
    projectId: 'nodepath',
    authDomain: 'nodepath.firebaseapp.com',
    storageBucket: 'nodepath.firebasestorage.app',
    measurementId: 'G-E428X8J3E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvgAuevU6A1AInVfvM6_aLjgv9lnf61vs',
    appId: '1:400224458947:android:2b99f208d310c9abc2aa76',
    messagingSenderId: '400224458947',
    projectId: 'nodepath',
    storageBucket: 'nodepath.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5VMLFa-cQu-s_mFQHYng6m88I4ev4L4c',
    appId: '1:400224458947:ios:642bfc78698db522c2aa76',
    messagingSenderId: '400224458947',
    projectId: 'nodepath',
    storageBucket: 'nodepath.firebasestorage.app',
    iosClientId: '400224458947-7nqdfmpij909rtjlldap2q428bo53inb.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5VMLFa-cQu-s_mFQHYng6m88I4ev4L4c',
    appId: '1:400224458947:ios:642bfc78698db522c2aa76',
    messagingSenderId: '400224458947',
    projectId: 'nodepath',
    storageBucket: 'nodepath.firebasestorage.app',
    iosClientId: '400224458947-7nqdfmpij909rtjlldap2q428bo53inb.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzw8I6aFYdp2v2Du_NRxlALQtTq9CHAc0',
    appId: '1:400224458947:web:9c335fada07db791c2aa76',
    messagingSenderId: '400224458947',
    projectId: 'nodepath',
    authDomain: 'nodepath.firebaseapp.com',
    storageBucket: 'nodepath.firebasestorage.app',
    measurementId: 'G-FNWGQCGTNX',
  );
}
